name = "ygleam"
version = "0.2.0"
licences = ["Apache-2.0"]
description = "Yjs Gleam Bindings"

gleam = "~> 1.0"
target = "javascript"

repository = { type = "github", user = "weedonandscott", repo = "gleam_yjs" }
links = [
  { title = "Yjs", href = "https://yjs.dev" },
  { title = "Used by Nestful", href = "https://nestful.app" },
  { title = "Developed by Weedon & Scott", href = "https://www.weedonandscott.com" },
]

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.19 or ~> 1.0"
gleam_json = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
